### ISSUE TITLE
[Bug] 更新picgo2.3.1后无法上传

### ISSUE THREAD

**Issue by love2wind** [d-w-x/picgo-plugin-gitlab-files#5]
# Issue Reoprt

## Describe
**Describe the bug(简述问题)**
今天更新Picgo2.3.1正式版以后上传错误

## Environment
**Desktop (please complete the following information):**
- OS: windows 10
- GUI
- Plugin version 1.1.6

## Log
**Log(日志)**
```
2022-11-13 23:10:57 [PicGo ERROR] 
------Error Stack Begin------
SyntaxError: Unexpected token o in JSON at position 1
    at JSON.parse (<anonymous>)
    at Object.handle (C:\Users\Administrator\AppData\Roaming\picgo\node_modules\picgo-plugin-gitlab-files\dist\index.js:146:31)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async $e.doUpload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:17170)
    at async $e.start (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:15941)
    at async Tt.upload (D:\PicGo\resources\app.asar\node_modules\picgo\dist\index.cjs.js:1:70737)
    at async Object.upload (D:\PicGo\resources\app.asar\background.js:2:653600)
    at async jn (D:\PicGo\resources\app.asar\background.js:2:656249)
-------Error Stack End------- 
```

## Additional
**Additional information(其他信息)**
我看picgo最新版更改了底层上传库，不知道是不是这个问题造成的。

**Comment by d-w-x** [comment]
我今天看看。

**Comment by d-w-x** [comment]
发了新版本， 1.2.2，你试试呢？

**Comment by love2wind** [comment]
> 发了新版本， 1.2.2，你试试呢？

搞定了，上传成功了，我用的极狐，刚又试了下gitlab，都可以了。
大佬效率很高啊，谢谢。

**Comment by d-w-x** [comment]
没事，感谢bug汇报。

核心问题是由于 1.5.0 的升级，[这里](https://github.com/d-w-x/picgo-plugin-gitlab-files/blob/master/src/index.ts#L169) 请求接口的返回值直接是 json 结构而不是字符串，因此不再需要 JSON.parse。

如果你在使用其他插件时出现类似问题可以将该信息提供给相关开发者参考。

**Comment by love2wind** [comment]
> 没事，感谢bug汇报。
> 
> 核心问题是由于 1.5.0 的升级，[这里](https://github.com/d-w-x/picgo-plugin-gitlab-files/blob/master/src/index.ts#L169) 请求接口的返回值直接是 json 结构而不是字符串，因此不再需要 JSON.parse。
> 
> 如果你在使用其他插件时出现类似问题可以将该信息提供给相关开发者参考。

好的。谢谢
